### ISSUE TITLE
No section: 'info'

### ISSUE THREAD

**Issue by Plazmaz** [torque59/nosqlpot#5]
I'm getting the following error when the 'info' command is issued to the redis honeypot:
```
Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
            return self._dataReceived(data)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/ec2-user/nosqlpot/redispot/redisdeploy.py", line 66, in dataReceived
            self.transport.write(rediscommands.parse_info(diff,self.connectionNb,cmd_count))
          File "/home/ec2-user/nosqlpot/redispot/redisconfig.py", line 87, in parse_info
            parser.set('info','uptime_in_seconds',str(time))
          File "/usr/lib64/python2.7/ConfigParser.py", line 753, in set
            ConfigParser.set(self, section, option, value)
          File "/usr/lib64/python2.7/ConfigParser.py", line 396, in set
            raise NoSectionError(section)
        ConfigParser.NoSectionError: No section: 'info'

2017-01-17 14:32:06-0500 [-] End connection:  No section: 'info'
```

**Comment by torque59** [comment]
@Plazmaz What configuration file are you using ?

**Comment by Plazmaz** [comment]
@torque59 I haven't touched the config, I'm just using 
`python nosqlpot.py -deploy redis -port 6379 -out redis.log`

**Comment by torque59** [comment]
@Plazmaz i am having a look at it.

**Comment by torque59** [comment]
@Plazmaz  fixed it and pushed an update, could you verify it. (the problem was, it could not find out the info file)

**Comment by Plazmaz** [comment]
Yep, that's been resolved. Thanks!
